/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it.unibas.carbonea.vista;

import it.unibas.carbonea.Applicazione;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author anton
 */
public class VistaFrame extends javax.swing.JFrame {

    /**
     * Creates new form VistaFrame
     */
    public VistaFrame() {
        //initComponents();
    }
    
    public void inizializza(){
        initComponents();
        initAzioni();
        this.setLocationRelativeTo(null);
        this.setContentPane(new JScrollPane(Applicazione.getInstance().getPannelloPrincipale()));
        this.pack();
        this.setVisible(true);
    }
    
    private void initAzioni(){
        this.menuExit.setAction(Applicazione.getInstance().getControlloPannelloPrincipale().getAzioneEsci());
        this.menuOpen.setAction(Applicazione.getInstance().getControlloPannelloPrincipale().getAzioneCaricaFile());
        this.menuCipherMetadati.setAction(Applicazione.getInstance().getControlloPannelloPrincipale().getAzioneCifraMetadati());
        this.menuCipherNomi.setAction(Applicazione.getInstance().getControlloPannelloPrincipale().getAzioneCifraNomi());
        this.menuCipherNumeri.setAction(Applicazione.getInstance().getControlloPannelloPrincipale().getAzioneCifraNumeri());
    }
    
    public void mostraMessaggioErrore(String errore){
        JOptionPane.showMessageDialog(this, errore, "Errore", JOptionPane.ERROR_MESSAGE);
    }
    
    public void mostraMessaggioInformativo(String messaggio){
        JOptionPane.showMessageDialog(this, messaggio, "Messaggio", JOptionPane.INFORMATION_MESSAGE);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuOpen = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCipherMetadati = new javax.swing.JMenuItem();
        menuCipherNomi = new javax.swing.JMenuItem();
        menuCipherNumeri = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        menuOpen.setText("jMenuItem1");
        jMenu1.add(menuOpen);

        menuExit.setText("jMenuItem1");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuCipherMetadati.setText("jMenuItem1");
        jMenu2.add(menuCipherMetadati);

        menuCipherNomi.setText("jMenuItem1");
        jMenu2.add(menuCipherNomi);

        menuCipherNumeri.setText("jMenuItem2");
        jMenu2.add(menuCipherNumeri);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuCipherMetadati;
    private javax.swing.JMenuItem menuCipherNomi;
    private javax.swing.JMenuItem menuCipherNumeri;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuOpen;
    // End of variables declaration//GEN-END:variables
}
